name: Cypress Tests

on:
  push:
    branches: [ Master, Cypress-tests, Automation-tests ]
  pull_request:
    branches: [ Master, Cypress-tests, Automation-tests ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start application
        run: npm run dev &
        env:
          NODE_ENV: development

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Cypress tests
        run: npx cypress run
